### ISSUE TITLE
Language setting not used

### ISSUE THREAD

**Issue by arsaboo** [yokingma/search_with_ai#12]
I have set the language to English. Yet, I see the output in Chinese language. 

![image](https://github.com/yokingma/search_with_ai/assets/18319734/1098bf0f-205e-487b-b6df-d007cb1279de)

**Comment by arsaboo** [comment]
It looks like the language is not set for deep search. A simple search returns the response in English.

**Comment by yokingma** [comment]
Thank you, I have updated the prompt, you can try again.

**Comment by arsaboo** [comment]
Ok...looks like it is working now 👍

**Comment by arsaboo** [comment]
Still not there

![image](https://github.com/yokingma/search_with_ai/assets/18319734/3d6f8ec7-903f-439d-93bb-c6c14f2cb772)
