### ISSUE TITLE
bug report: 追问时的 搜索&引用问题

### ISSUE THREAD

**Issue by getofferhelp** [yokingma/search_with_ai#21]
如果问过一个问题后，再追问，会有这两个情况出现：

1，不显示引用，如图一

2，引用的标记是假引用，如图二。

我在看那个farfalle 项目的提示词，不知道咋整的

<img width="680" alt="bug report 1" src="https://github.com/yokingma/search_with_ai/assets/13744916/2dded9dd-735f-4813-9387-4b799c3ec341">
<img width="701" alt="bug report 2" src="https://github.com/yokingma/search_with_ai/assets/13744916/094d2bca-2281-4d43-8c84-1b87475d4e4e">

**Comment by yokingma** [comment]
对，追问的情况确实是这样，一直没时间优化。我可能会直接去掉追问时候的引用内容。

**Comment by getofferhelp** [comment]
那个farfalle 还行，可以作为参考。不过那个语言支持不对，中文提问会时不时的用英文回答

**Comment by yokingma** [comment]
@getofferhelp 周末我看下，借鉴一下。

**Comment by getofferhelp** [comment]
> @getofferhelp 周末我看下，借鉴一下。

我在看他的提示词，"俺寻思"一下，看看能不能搞定，哈哈哈

之前说的“点击相关问题后页面刷新”那个问题，我现在理解你的思路了，是不是：当前搜索得到的信息可以在下面继续追问，追问的回答继续参考本次搜索所得、但是点击相关问题后就是另一次搜索，所以要重开。

这样的话每一次搜索所得信息本身就是个小的工作区/资料库，这个思路之前我没理解

如果确实这个思路的话我觉得之前那个提议“点击相关问题后的页面不刷新、相关问题的问答保留在当前页面的对话记录”，就不对了。

不过还是需要做修改，就是 点击相关问题后，直接打开一个浏览器页面，这样第一次搜索的问答不会被刷掉。加个 _blank可以不，还是要大改啊（好吧，暴露了我并不懂代码的事实 - -

我先去找找这部分代码看看

------分割线----

二维码失效了啊，进不去群了。。。

其实我是想请教，如果想在线部署的话，那个searXNG的 host哪来的啊大佬  T T

**Comment by getofferhelp** [comment]
啊对，还有那个 搜索引擎指定搜索某个网站内容这个特性，好想拥有啊 T T

**Comment by yokingma** [comment]
![WechatIMG192](https://github.com/yokingma/search_with_ai/assets/8767820/dd597e55-ed8c-4592-9255-5e9602d5d3c0)
@getofferhelp  试试这个

**Comment by getofferhelp** [comment]
来了来了！

**Comment by yokingma** [comment]
修复了引用显示的问题了：）
