### ISSUE TITLE
界面效果优化

### ISSUE THREAD

**Issue by andyliu91** [yokingma/search_with_ai#30]
问题搜索后，界面大概会有5-6S的空白等待时间，用户体验干不高，可以借鉴秘塔的搜索提示
![image](https://github.com/yokingma/search_with_ai/assets/48175431/e5fe232a-eca1-4e15-a3da-b78eecc18f56)
![image](https://github.com/yokingma/search_with_ai/assets/48175431/2bb7da7f-4a4b-4b82-9719-cfd9bc92abdb)

**Comment by spammenotinoz** [comment]
I don't have this issue, this project is highly responsive, perhaps your server needs more resources?
