### ISSUE TITLE
搜索引擎建议添加 jina.ai

### ISSUE THREAD

**Issue by forrany** [yokingma/search_with_ai#36]
[Reader API](https://jina.ai/reader/#apiform)

Reader API 不仅免费，功能强大，甚至能读取 PDF，其 s.jina.ai 可用于内容搜索； r.jina.ai 用于网站内容读取，返回的内容 LLM 友好

<img width="1561" alt="image" src="https://github.com/yokingma/search_with_ai/assets/29779326/2b2a12e5-56bf-46af-bcee-c8b266b64b94">

<img width="1651" alt="image" src="https://github.com/yokingma/search_with_ai/assets/29779326/44a46dcf-f54e-421d-9073-1765d2e5f80c">

**Comment by yokingma** [comment]
我研究一下😁👍

**Comment by yokingma** [comment]
一直没时间，最近才加上jina.ai ...
