### ISSUE TITLE
服务器无法访问GOOGLE，搜索引擎该怎么替换呢？

### ISSUE THREAD

**Issue by wufxgtihub123** [yokingma/search_with_ai#39]
在服务器上部署了相关服务，然后搜索时就报错：
![image](https://github.com/yokingma/search_with_ai/assets/74227869/3ed5add5-ae8b-4d9c-91d4-64c502b87310)
请问有什么好的方案吗？
另外，交流群的二维码过期了，可以请大佬更新一下吗？谢谢

**Comment by yokingma** [comment]
服务器必须得能访问到才行啊（要么自己做个中转），要么只能换比如BING了...
![WechatIMG234](https://github.com/yokingma/search_with_ai/assets/8767820/91e3fbfd-c476-430f-9d07-e2f3d6bd42b8)
