### ISSUE TITLE
希望添加上下文的功能

### ISSUE THREAD

**Issue by hallfay0** [yokingma/search_with_ai#4]
HI，已经用上了您的这个搜索，目前当成半主力使用，结合本地的ollama来使用体验非常好，我想问您这是否有给项目添加上下文的功能，例如我问：从大阪机场到心斋桥怎么走，根据提供的回答我可以直接追问，哪一路电车？

**Comment by yokingma** [comment]
谢谢你的建议😊，上下文能力正在优化，前天增加了根据搜索上下文追问的功能，但不是完整的会话上下文。
可能今天晚点会更新优化后的上下文能力。

**Comment by hallfay0** [comment]
> 谢谢你的建议😊，上下文能力正在优化，前天增加了根据搜索上下文追问的功能，但不是完整的会话上下文。 可能今天晚点会更新优化后的上下文能力。

多谢多谢，等更新完成后关闭这个话题

**Comment by yokingma** [comment]
@hallfay0 试试上下文能力，更新了

**Comment by hallfay0** [comment]
> @hallfay0 试试上下文能力，更新了

感谢提醒，已经更新，正在使用。您这里的上下文指的是回答后 “相关” 内自动生成的追问可以携带上完整上文内容，现在刚开始使用还未发现问题，使用体验挺好。
我说的还有一种上下文指的是，用户可以自行针对AI的回答进行追问，AI携带了对上文的记忆，类似我的提问：“从大阪机场到心斋桥怎么走”，"AI告诉我从机场坐电车到日本桥，再打出租车.......".  根据AI搜索提供的回答我可以直接追问:“哪一路电车”,或者”出租车的车费大概多少“，AI是明白我是在根据他上面的回答来追问，大体就是这个意思。因为有很多时候单纯的一次问答是没有解决问题的，需要根据回答来进行补充追问。当然这个可能是您更后期才考虑的了。

**Comment by yokingma** [comment]
> > @hallfay0 试试上下文能力，更新了
> 
> 感谢提醒，已经更新，正在使用。您这里的上下文指的是回答后 “相关” 内自动生成的追问可以携带上完整上文内容，现在刚开始使用还未发现问题，使用体验挺好。 我说的还有一种上下文指的是，用户可以自行针对AI的回答进行追问，AI携带了对上文的记忆，类似我的提问：“从大阪机场到心斋桥怎么走”，"AI告诉我从机场坐电车到日本桥，再打出租车.......". 根据AI搜索提供的回答我可以直接追问:“哪一路电车”,或者”出租车的车费大概多少“，AI是明白我是在根据他上面的回答来追问，大体就是这个意思。因为有很多时候单纯的一次问答是没有解决问题的，需要根据回答来进行补充追问。当然这个可能是您更后期才考虑的了。

是不是在进行新的搜索会话的时候携带对上一次搜索的记忆？

**Comment by hallfay0** [comment]
> > > @hallfay0 试试上下文能力，更新了
> > 
> > 感谢提醒，已经更新，正在使用。您这里的上下文指的是回答后 “相关” 内自动生成的追问可以携带上完整上文内容，现在刚开始使用还未发现问题，使用体验挺好。 我说的还有一种上下文指的是，用户可以自行针对AI的回答进行追问，AI携带了对上文的记忆，类似我的提问：“从大阪机场到心斋桥怎么走”，"AI告诉我从机场坐电车到日本桥，再打出租车.......". 根据AI搜索提供的回答我可以直接追问:“哪一路电车”,或者”出租车的车费大概多少“，AI是明白我是在根据他上面的回答来追问，大体就是这个意思。因为有很多时候单纯的一次问答是没有解决问题的，需要根据回答来进行补充追问。当然这个可能是您更后期才考虑的了。
> 
> 是不是在进行新的搜索会话的时候携带对上一次搜索的记忆？

是的，在当前页面的所有搜索携带所有的搜索记忆，直到主动结束当前会话。如果需要开启新搜索，可以回到主页或者清除上文记忆。但是这个可能会对上下文长度产生挑战。

我不是专业开发者，提供的只是我对这个项目的使用理解，您可以参考，我说的不一定靠谱。

**Comment by yokingma** [comment]
> > > > @hallfay0 试试上下文能力，更新了
> > > 
> > > 
> > > 感谢提醒，已经更新，正在使用。您这里的上下文指的是回答后 “相关” 内自动生成的追问可以携带上完整上文内容，现在刚开始使用还未发现问题，使用体验挺好。 我说的还有一种上下文指的是，用户可以自行针对AI的回答进行追问，AI携带了对上文的记忆，类似我的提问：“从大阪机场到心斋桥怎么走”，"AI告诉我从机场坐电车到日本桥，再打出租车.......". 根据AI搜索提供的回答我可以直接追问:“哪一路电车”,或者”出租车的车费大概多少“，AI是明白我是在根据他上面的回答来追问，大体就是这个意思。因为有很多时候单纯的一次问答是没有解决问题的，需要根据回答来进行补充追问。当然这个可能是您更后期才考虑的了。
> > 
> > 
> > 是不是在进行新的搜索会话的时候携带对上一次搜索的记忆？
> 
> 是的，在当前页面的所有搜索携带所有的搜索记忆，直到主动结束当前会话。如果需要开启新搜索，可以回到主页或者清除上文记忆。但是这个可能会对上下文长度产生挑战。
> 
> 我不是专业开发者，提供的只是我对这个项目的使用理解，您可以参考，我说的不一定靠谱。

是的，这对上下文长度确实是个挑战，我会考虑如何更好的实现它

**Comment by hallfay0** [comment]
谢谢开发者的努力，相当快速的就跟新了第一版，所以我将关闭这个话题。
