### ISSUE TITLE
HELP!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by An252315** [yokingma/search_with_ai#41]
[+] Building 4.0s (6/6) FINISHED                                                                                             docker:default
 => [search internal] load .dockerignore                                                                                               0.0s
 => => transferring context: 34B                                                                                                       0.0s
 => [search internal] load build definition from Dockerfile                                                                            0.0s
 => => transferring dockerfile: 699B                                                                                                   0.0s
 => ERROR [search internal] load metadata for docker.io/library/node:18-alpine                                                         4.0s
 => CANCELED [search internal] load metadata for docker.io/library/node:18                                                             4.0s
 => [search auth] library/node:pull token for registry-1.docker.io                                                                     0.0s
 => [search auth] library/node:pull token for registry-1.docker.io                                                                     0.0s
------
 > [search internal] load metadata for docker.io/library/node:18-alpine:
------
failed to solve: node:18-alpine: failed to authorize: failed to fetch oauth token: Post "https://auth.docker.io/token": proxyconnect tcp: dial tcp: lookup https: no such host
`docker-compose` 进程结束，退出代码为 17

**Comment by yokingma** [comment]
这应该是docker的问题吧

**Comment by An252315** [comment]
> 这应该是docker的问题吧
行，那我重新装一下docker吧

**Comment by An252315** [comment]
> > > 这应该是docker的问题吧
> > > 行，那我重新装一下docker吧
> 
> 也不一定要重装... 可以去docker社区问一下

您的docker镜像源配置是啥啊

**Comment by yokingma** [comment]
现在国内都没法用了，我都是直接翻。

**Comment by An252315** [comment]
这个怎么翻😳



---Original---
From: ***@***.***&gt;
Date: Sat, Jul 13, 2024 17:05 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yokingma/search_with_ai] HELP!!!!!!!!!!!!!!!!!!!!!!!!! (Issue#41)




 
现在国内都没法用了，我都是直接翻。

**Comment by yokingma** [comment]
> 这个怎么翻😳
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sat, Jul 13, 2024 17:05 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [yokingma/search_with_ai] HELP!!!!!!!!!!!!!!!!!!!!!!!!! (Issue#41) 现在国内都没法用了，我都是直接翻。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

或者你问的是dockerfile中的npm镜像源？这个没配置，默认的。
还是你问的是docker hub？

**Comment by yokingma** [comment]
> 这个怎么翻😳
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sat, Jul 13, 2024 17:05 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [yokingma/search_with_ai] HELP!!!!!!!!!!!!!!!!!!!!!!!!! (Issue#41) 现在国内都没法用了，我都是直接翻。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

或者你问的是dockerfile中的npm镜像源？这个没配置，默认的。
还是你问的是docker hub？
