### ISSUE TITLE
如何更换默认的GPT3.5接口

### ISSUE THREAD

**Issue by tianins** [yokingma/search_with_ai#42]
你好，我想要使用阿里的qwen模型，在.env.docker中增加了qwen的key，但是重新运行docker compose up -d 后，还是GPT3.5接口。是需要做额外的配置吗？

**Comment by yokingma** [comment]
项目集成了很多个模型的API，可能你启动后需要手动选择某个模型，或者env.docker中删除openai的key。
配置多个key，启动后需要手动选择。（提示：项目启动后打开页面，右侧有个设置的按钮）。
