### ISSUE TITLE
对话框允许输入的长度很短

### ISSUE THREAD

**Issue by Jiayou-Chao** [yokingma/search_with_ai#48]
对话框似乎只能输入最多100个字符，而且无法换行。希望能够改进。

**Comment by yokingma** [comment]
增加了字数限制，另外也可以修改：```web/src/components/searchInputBar.vue```

**Comment by Jiayou-Chao** [comment]
好像还是不行，还是限制在100字符

**Comment by yokingma** [comment]
@Jiayou-Chao 你更新项目看看，你也可以修改```web/src/components/searchInputBar.vue``` 里面的数值：
```ts
const props = withDefaults(defineProps<Props>(), {
  limit: 520
});
```
