### ISSUE TITLE
AI回答不返回消息

### ISSUE THREAD

**Issue by wzlzking** [yokingma/search_with_ai#51]
我使用的是百度文心一言的AI模型，配置的BAIDU_KEY和BAIDU_SECRET，我确认是没问题的，因为我将打印出来的参数放到postman里请求是可以返回接口的，请问这是什么问题啊

![image](https://github.com/user-attachments/assets/5fa35ed4-ef60-4e18-85b3-6cbb4d729ea9)
![image](https://github.com/user-attachments/assets/f7fc088e-42af-4240-adc4-130ce9501f66)

**Comment by yokingma** [comment]
我检查下百度的接口，百度有段时间没更新了...

**Comment by wzlzking** [comment]
但是我使用打印出来的url和message直接在postman请求，是会返回结果的

![image](https://github.com/user-attachments/assets/53e8b886-df62-4494-8794-6b09371fa23b)

**Comment by wzlzking** [comment]
已解决，根据百度文档修改了一下代码，使用新的模型就可以了
![image](https://github.com/user-attachments/assets/1feb6ab8-9494-4b3d-a26e-ffed69f0fd86)

**Comment by yokingma** [comment]
@wzlzking 好的 👍

**Comment by Statisticss** [comment]
qwen好像也有同样的问题，现有代码中的接口不好使了
