### ISSUE TITLE
可不可以增加api调用功能

### ISSUE THREAD

**Issue by yangbo968** [yokingma/search_with_ai#55]

**Comment by 520yd** [comment]
可以调用沉浸式翻译吗

yangbo968 ***@***.***> 于 2024年9月20日周五 18:00写道：

**Comment by yokingma** [comment]
其实项目本身就是前后分离的，有API, 只是没专门文档写出来。
```/backend/app.ts``` 和 ```/backend/controllers.ts``` 可以看下。

**Comment by yangbo968** [comment]
> 其实项目本身就是相互独立的，有API，只是没有专门的文档写出来。 `/backend/app.ts`并且`/backend/controller.ts`可以看下。

可以出一个文本教学吗，那中Java和python调用的，测试了好几个开源项目，就当前这个最顺手了

**Comment by yokingma** [comment]
最近有点忙 周末我写个文档吧

**Comment by yokingma** [comment]
已经更新了部分API文档说明 [API](https://github.com/yokingma/search_with_ai/blob/main/README_CN.md)  @yangbo968
