### ISSUE TITLE
添加oneapi模型問題 

### ISSUE THREAD

**Issue by SakurajimaMai-1202** [yokingma/search_with_ai#56]
目前已經有把openai_key 跟OPENAI_PROXY_URL 替換成自架的oneapi 
但是如何添加模型呢? 已經有嘗試去更改\backend\utils\constant.ts 但改完重新佈署也沒有新增 
還是我部署上有問題? 
部屬環境 群暉nas上的docker  使用protainer佈署 有嘗試添加環境變量與掛載資料夾進去
![PixPin_2024-09-27_13-39-50](https://github.com/user-attachments/assets/f6c19f96-2861-470a-8c85-c313c0e2797d)
![PixPin_2024-09-27_13-38-01](https://github.com/user-attachments/assets/57fa031c-82d9-4006-b72d-a6a5c1e831ff)
![PixPin_2024-09-27_13-45-18](https://github.com/user-attachments/assets/5dda43cb-4855-49a6-abaf-d7ac26ec7c8a)

**Comment by yokingma** [comment]
是修改的.env.docker配置文件吗？
增加模型是这儿没错的：```\backend\utils\constant.ts ```

**Comment by SakurajimaMai-1202** [comment]
> 是修改的.env.docker配置文件吗？ 增加模型是这儿没错的：`\backend\utils\constant.ts `

是的 我想用one api調用 正常來說應該是要把key 輸入在open ai key  然後再打上proxy url
但網頁上顯示不出來 要調用的model 
因此我想要去增加模型 但實際上在\backend\utils\constant.ts 增加後 重新再建立一次 並沒有抓到新增的models

**Comment by SakurajimaMai-1202** [comment]
> 是修改的.env.docker配置文件吗？ 增加模型是这儿没错的：`\backend\utils\constant.ts `

好像是沒修改到 但這文件要怎麼添加模型的部分?
![PixPin_2024-10-02_16-26-38](https://github.com/user-attachments/assets/8d033a77-2af7-4045-9a33-0476203bbf22)

**Comment by SakurajimaMai-1202** [comment]
> 项目做了部分更新，增加模型在`/backend/model.ts`文件中修改即可。
我甚至都把原本都刪光了 重新佈署 選擇模型還是一樣 
還是我不能單獨使用自訂的openai key+open ai base url?
![PixPin_2024-10-07_17-34-51](https://github.com/user-attachments/assets/9e04127a-0321-491b-a20b-1753f4d12bd7)
![PixPin_2024-10-07_17-36-38](https://github.com/user-attachments/assets/152c3351-af06-46c4-bbe7-acabd98fb578)

**Comment by yokingma** [comment]
> > 项目做了部分更新，增加模型在`/backend/model.ts`文件中修改即可。
> > 我甚至都把原本都刪光了 重新佈署 選擇模型還是一樣
> > 還是我不能單獨使用自訂的openai key+open ai base url?
> > ![PixPin_2024-10-07_17-34-51](https://private-user-images.githubusercontent.com/56517823/374114378-9e04127a-0321-491b-a20b-1753f4d12bd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTQ4MzcsIm5iZiI6MTcyODI5NDUzNywicGF0aCI6Ii81NjUxNzgyMy8zNzQxMTQzNzgtOWUwNDEyN2EtMDMyMS00OTFiLWEyMGItMTc1M2Y0ZDEyYmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDA5NDg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3Njk1ODI2YjM3MDVhNDlmY2JlNGQzNWM0YzMzMTk0MjZiNTg5MjM3ZWIzNDg5MWI3ODQ4ZmI2ZDZiNmIwMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.67Y2gNYWuWTnNcqRmA22y4_77eJUTE6Rp_TKFY3gzlI)
> > ![PixPin_2024-10-07_17-36-38](https://private-user-images.githubusercontent.com/56517823/374114804-152c3351-af06-46c4-bbe7-acabd98fb578.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTQ4MzcsIm5iZiI6MTcyODI5NDUzNywicGF0aCI6Ii81NjUxNzgyMy8zNzQxMTQ4MDQtMTUyYzMzNTEtYWYwNi00NmM0LWJiZTctYWNhYmQ5OGZiNTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDA5NDg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmOTQ5ZjVlODFlNjhlZmVmYTdhNmFhYjQ0MjI1MDNlMWNiODZmZDZkMzRkNzE2NjNhNmQzODI2NjVlNGNlMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Nakow4USq_U9bYPNBE_3VESnBweyUBOP9IQ9wU6bbls)

```openai key&baseurl```都是可以使用的，我也一直在用。

```.env.docker```是使用docker compose部署的环境配置文件，```model.ts```文件修改后需要重新构建镜像。
你可以先试试直接在本地跑项目测试下，需要配置```.env```文件，另外如果项目根目录有```/dist```文件夹，可以删除。

**Comment by SakurajimaMai-1202** [comment]
> > > 项目做了部分更新，增加模型在`/backend/model.ts`文件中修改即可。
> > > 我甚至都把原本都刪光了 重新佈署 選擇模型還是一樣
> > > 還是我不能單獨使用自訂的openai key+open ai base url?
> > > ![PixPin_2024-10-07_17-34-51](https://private-user-images.githubusercontent.com/56517823/374114378-9e04127a-0321-491b-a20b-1753f4d12bd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTQ4MzcsIm5iZiI6MTcyODI5NDUzNywicGF0aCI6Ii81NjUxNzgyMy8zNzQxMTQzNzgtOWUwNDEyN2EtMDMyMS00OTFiLWEyMGItMTc1M2Y0ZDEyYmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDA5NDg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3Njk1ODI2YjM3MDVhNDlmY2JlNGQzNWM0YzMzMTk0MjZiNTg5MjM3ZWIzNDg5MWI3ODQ4ZmI2ZDZiNmIwMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.67Y2gNYWuWTnNcqRmA22y4_77eJUTE6Rp_TKFY3gzlI)
> > > ![PixPin_2024-10-07_17-36-38](https://private-user-images.githubusercontent.com/56517823/374114804-152c3351-af06-46c4-bbe7-acabd98fb578.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTQ4MzcsIm5iZiI6MTcyODI5NDUzNywicGF0aCI6Ii81NjUxNzgyMy8zNzQxMTQ4MDQtMTUyYzMzNTEtYWYwNi00NmM0LWJiZTctYWNhYmQ5OGZiNTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDA5NDg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmOTQ5ZjVlODFlNjhlZmVmYTdhNmFhYjQ0MjI1MDNlMWNiODZmZDZkMzRkNzE2NjNhNmQzODI2NjVlNGNlMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Nakow4USq_U9bYPNBE_3VESnBweyUBOP9IQ9wU6bbls)
> 
> `openai key&baseurl`都是可以使用的，我也一直在用。
> 
> `.env.docker`是使用docker compose部署的环境配置文件，`model.ts`文件修改后需要重新构建镜像。 你可以先试试直接在本地跑项目测试下，需要配置`.env`文件，另外如果项目根目录有`/dist`文件夹，可以删除。

目前model.ts修改後 有重新構建镜像 但改不過去   正常來說應該就是改model.ts內 修改openai模型表 重新構建鏡像 網頁上應該就會顯示出來不是嗎? 像我這邊是將整個openai模型列表都刪掉 僅剩下Qwen 2.5 7B一個，但網頁上卻還是把原本列表上的給帶入了?
![PixPin_2024-10-07_18-37-18](https://github.com/user-attachments/assets/ae9bba61-9bf2-4fd4-8cac-09ac0efdfe00)
 
![PixPin_2024-10-07_18-37-57](https://github.com/user-attachments/assets/d3088a44-b4d0-4887-8800-8c837a11605c)

**Comment by yokingma** [comment]
@SakurajimaMai-1202 说明你构建的时候```yarn run build```的结果还是旧的内容，文件修改没有生效。
我想可能是没有删除旧的镜像文件，另外Dockerfile文件最近更新过，请你试一试重新pull一下更新项目再尝试下。
另外前端网页也清空下缓存。

如果还是不可以你先试试运行我预构建的镜像是否跑的起来: ```/docker``` 文件夹下面直接运行```docker compose up -d```， 如果修改配置```.env.docker```，只需要重启容器即可生效。

**Comment by yokingma** [comment]
> 如果项目根目录有/dist文件夹请先删除

我的修改示例是：

model.ts
```ts
{
  platform: 'openai',
  type: 'openai',
  models: ['Qwen/Qwen2.5-7B-Instruct', 'o1-preview', 'o1-mini', 'gpt-4o', 'gpt-4o-mini', 'gpt-4o-latest', 'gpt-4-preview', 'gpt-4-turbo', 'gpt-4', 'gpt-3.5-turbo']
},
```

.env.docker (非docker构建修改.env)
```env
# openai
OPENAI_KEY=sk-n5k54iURtRmQ7BN68c****************
OPENAI_PROXY_URL=https://xxx.xxx.com/v1
```

上面是有效的：
![WX20241008-134618@2x](https://github.com/user-attachments/assets/51172cd3-a178-4c55-bcaf-b5a268e83fd4)

**Comment by yokingma** [comment]
今晚会做一下升级，把model.ts 调整为model.json挂载到docker, 这样修改添加model就不需要重复构建了。

**Comment by SakurajimaMai-1202** [comment]
> 今晚会做一下升级，把model.ts 调整为model.json挂载到docker, 这样修改添加model就不需要重复构建了。

那我等一下升級吧，蠻怪異的 剛剛有再根據你的做測試一樣是改不過去 ，不知道是不是我的過程有誤 

目前過程方式
1.clone 你這個專案 
2. .env.docker文件修改 填上 openai key &PROXY_URL 
3. model.ts修改 在openai的地方多添加上'Qwen/Qwen2.5-7B-Instruct',
4.在docker資料夾 cmd 輸入 docker compose up -d 啟動

**Comment by yokingma** [comment]
@SakurajimaMai-1202  项目更新了 预构建镜像```zacma/aisearch:arm64``` ```zacma/aisearch:amd64``` 暂时没合并，按需pull吧，配置只需要修改```/docker```下面的model.json即可，我本地测试了可以。

**Comment by SakurajimaMai-1202** [comment]
> @SakurajimaMai-1202  项目更新了 预构建镜像```zacma/aisearch:arm64``` ```zacma/aisearch:amd64``` 暂时没合并，按需pull吧，配置只需要修改```/docker```下面的model.json即可，我本地测试了可以。
感謝大佬 剛剛測試過確實可以了
