### ISSUE TITLE
微信交流群扫码不能进了

### ISSUE THREAD

**Issue by ZJYCP** [yokingma/search_with_ai#61]
扫码显示超过200人需要邀请才能进入， 请问还有什么途径可以进群
或者可以考虑开放一些另外的沟通渠道

**Comment by yokingma** [comment]
![WechatIMG309](https://github.com/user-attachments/assets/cae856d1-a8cc-4f43-8c4f-5ce273014aef)
群满了... 暂时先加这个微信拉进群
