### ISSUE TITLE
Error on chat

### ISSUE THREAD

**Issue by Haneshagvs** [yokingma/search_with_ai#63]
Please fix this bro i need your ai
![Screenshot_20241010-200618](https://github.com/user-attachments/assets/f5651cd7-f624-4986-8952-7a1be22f0ef6)

**Comment by yokingma** [comment]
previous API was invalid, gonna update soon. thanks for your reminder.

**Comment by Haneshagvs** [comment]
Ok thank you for creating 👋

**Comment by yokingma** [comment]
@Haneshagvs When my server connected to the API server(cloudflare), it encountered a 403 error. I am looking for the reason, this may take some time...
