### ISSUE TITLE
网页提取的内容是不是太少了

### ISSUE THREAD

**Issue by Statisticss** [yokingma/search_with_ai#69]
看代码目前似乎只是用了搜索引擎给出的页面snippet提供给大模型，这样子信息是否不全呀？
是不是得再基于url爬取网页的全部文字内容会更好一些？没有实现这个是时间开销/token开销方面的考虑么？

**Comment by yokingma** [comment]
对，另外是想要增加全文提取能力的，只是目前空闲时间太少了：）

**Comment by Statisticss** [comment]
明白了，期待一下全文提取功能~
