### ISSUE TITLE
大佬，能给一个本地编译的版本么，或者给rainbond.cc上给放一个镜像

### ISSUE THREAD

**Issue by brewswang** [yokingma/search_with_ai#70]
zacma/aisearch pull 不下来，能给一个本地编译的版本么，或者给rainbond.cc上给放一个镜像。
 ded while awaiting headers)
(py39) [root@VM-16-13-tencentos docker]# docker pull zacma/aisearch
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by brewswang** [comment]
谢谢

**Comment by brewswang** [comment]
使用yarn run start 启动的服务经常挂了，不稳定

**Comment by yokingma** [comment]
https://cnb.cool/aigc/AiSearch 我在这个腾讯的平台上有个镜像 可以下 :)

**Comment by brewswang** [comment]
非常感谢，可以正常拉取镜像

> https://cnb.cool/aigc/AiSearch 我在这个腾讯的平台上有个镜像 可以下 linux/amd64 `docker.cnb.cool/aigc/aisearch:latest`
