### ISSUE TITLE
docker image pull not find in x86

### ISSUE THREAD

**Issue by szkane** [yokingma/search_with_ai#80]
[+] Running 1/1
 ✘ search Error manifest for zacma/aisearch:latest not found: manifest unknown: manifest unknown

**Comment by yokingma** [comment]
```docker pull zacma/aisearch:amd64```
```docker pull zacma/aisearch:arm64```

**Comment by yokingma** [comment]
最新的镜像地址：```docker pull docker.cnb.cool/aigc/aisearch```
