### ISSUE TITLE
请问，能让容器里web前端指向本机web前端目录吗

### ISSUE THREAD

**Issue by qq430968** [yokingma/search_with_ai#86]
/root/search_with_ai/web 这是我本机web路径
/root/search_with_ai/docker 这是本机docker目录

要怎么搞才能让容器里面的前端指向到本机的web前端
我自己试了下，打开前端是空白的，应该是路径问题

**Comment by yokingma** [comment]
搞定了吗 👍

**Comment by qq430968** [comment]
搞定了
