### ISSUE TITLE
本地ollama调用远程服务器地址可以使用吗

### ISSUE THREAD

**Issue by lonngxiang** [yokingma/search_with_ai#9]

**Comment by lonngxiang** [comment]
本地有模型没改.env 运行也报错
![image](https://github.com/yokingma/search_with_ai/assets/40717349/7b4d6c73-dc57-49cc-bb62-4918ab373597)
![image](https://github.com/yokingma/search_with_ai/assets/40717349/cb1c93ed-d339-4913-a4a8-1fd7c1b0689f)

**Comment by yokingma** [comment]
如果你不是docker部署的话，只需要修改.env的ollama为它的host地址就可以了。

**Comment by lonngxiang** [comment]
> 如果你不是docker部署的话，只需要修改.env的ollama为它的host地址就可以了。

改成ip地址也不行

**Comment by yokingma** [comment]
比如
```.env
OLLAMA_HOST=http://[OLLAMA的服务器IP地址]:11434
```
当然如果你端口改了，也要修改端口。

**Comment by lonngxiang** [comment]
![image](https://github.com/yokingma/search_with_ai/assets/40717349/76529959-ad36-445f-ba0c-240fd47c97cd)

**Comment by lonngxiang** [comment]
> 比如
> 
> ```dotenv
> OLLAMA_HOST=http://[OLLAMA的服务器IP地址]:11434
> ```
> 
> 当然如果你端口改了，也要修改端口。

是的，没改端口；运行还是不行

**Comment by lonngxiang** [comment]
搜索不到模型，我看你.env 只需要写地址，不用指定模型名
![image](https://github.com/yokingma/search_with_ai/assets/40717349/4b4c6783-d0ba-4a61-b4cd-8071a8786789)

**Comment by yokingma** [comment]
> 搜索不到模型，我看你.env 只需要写地址，不用指定模型名 ![image](https://private-user-images.githubusercontent.com/40717349/329764224-4b4c6783-d0ba-4a61-b4cd-8071a8786789.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTQxMjAsIm5iZiI6MTcxNTQxMzgyMCwicGF0aCI6Ii80MDcxNzM0OS8zMjk3NjQyMjQtNGI0YzY3ODMtZDBiYS00YTYxLWI0Y2QtODA3MWE4Nzg2Nzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA3NTAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjOGU3MTU1ZGI5NzJkZThiZjk3Yzc5OWQ2ZjhkZmM5YzU4NTM3NzNhYzI4YmZlMDE3NDc1MDRkNWZlZmI1YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IU4n_CN341ZZ4oQAhOuA1YW6oNCCKc6dPPcmAss_PZQ)

不需要指定，生效的话这里会列出来模型 ，改的是.env吧？

**Comment by yokingma** [comment]
改完试试重启下服务。

**Comment by lonngxiang** [comment]
改的是env
![image](https://github.com/yokingma/search_with_ai/assets/40717349/2f7a73a3-b76f-4226-af01-2bd610ca5784)

**Comment by lonngxiang** [comment]
> 改完试试重启下服务。

已经down然后再up，也不行

**Comment by lonngxiang** [comment]
![image](https://github.com/yokingma/search_with_ai/assets/40717349/63a4dba8-fc41-4919-b971-7c16a0484da7)

**Comment by yokingma** [comment]
![WechatIMG167](https://github.com/yokingma/search_with_ai/assets/8767820/fb7360d6-a67f-468e-b161-db52efb2f80d)
不然你加个群里说吧。
