### ISSUE TITLE
根据部署指引部署,不显示模型

### ISSUE THREAD

**Issue by jingshaoxiang** [yokingma/search_with_ai#90]
$ dotenvx run --env-file=.env -- node ./dist/app.js
[dotenvx@0.24.0] injecting env (28) from .env
{"level":"info","message":"[Server is running on port]: 3000"}
yarn run v1.22.22
$ dotenvx run --env-file=.env -- node ./dist/app.js
[dotenvx@0.24.0] injecting env (28) from .env
{"level":"info","message":"[Server is running on port]: 3000"}
[whiteListMiddleware] [] search.master-jsx.top
[server error] Error: model is required
    at new Rag (/app/dist/rag/index.js:18:19)
    at searchController (/app/dist/controller.js:40:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/middleware.js:11:20
    at async /app/dist/app.js:37:9
    at async cors (/app/node_modules/@koa/cors/index.js:109:16)
    at async serve (/app/node_modules/koa-static/index.js:53:9)
yarn run v1.22.22
$ dotenvx run --env-file=.env -- node ./dist/app.js
[dotenvx@0.24.0] injecting env (28) from .env
{"level":"info","message":"[Server is running on port]: 3000"}

**Comment by yokingma** [comment]
我看报错是```[server error] Error: model is required```，在请求的时候没传模型名称参数，自己配置的大模型服务的key吗？手动选一下模型呢

**Comment by yokingma** [comment]
看你的具体代理配置，一般不是都加/v1的吗，还是你的代理中转不需要？

**Comment by jingshaoxiang** [comment]
> 看你的具体代理配置，一般不是都加/v1的吗，还是你的代理中转不需要？

加了v1也不行 首页上出不来模型选项
![图片](https://github.com/user-attachments/assets/242b61eb-8ed6-4a3e-8452-f25ebe82651a)

**Comment by yokingma** [comment]
你是本地dev模式吧，修改的是哪个.dev文件？

**Comment by jingshaoxiang** [comment]
> 你是本地dev模式吧，修改的是哪个.dev文件？

我是docker-compose启动的,修改的是 .env.docker 这个配置文件

**Comment by yokingma** [comment]
我刚构建了一个新的制品，不然你先试试这个 ```docker pull docker.cnb.cool/aigc/aisearch```

**Comment by jingshaoxiang** [comment]
> 我刚构建了一个新的制品，不然你先试试这个 `docker pull docker.cnb.cool/aigc/aisearch`

好嘞 谢谢大佬

**Comment by jingshaoxiang** [comment]
> docker.cnb.cool/aigc/aisearch

大佬还是不行 出不来

**Comment by jingshaoxiang** [comment]
> 我刚构建了一个新的制品，不然你先试试这个 `docker pull docker.cnb.cool/aigc/aisearch`

自己电脑上重新搞了一份新的,也是一样的情况TaT

**Comment by yokingma** [comment]
加个微信吧

![wechat](https://github.com/user-attachments/assets/a12d88db-b313-4017-87a3-57a2cefe4449)

**Comment by jingshaoxiang** [comment]
> 不好意思 配置写错了，
> 
> ```
>     volumes:
>       - ./.env.docker:/app/.env
>       - ./model.json:/app/dist/model.json
> ```

解决啦 解决啦
